NUM_OPTIONS = 4

# TextQA

MAX_OUTPUT_LEN_MC = 15
MAX_OUTPUT_LEN_ANSWER_ONLY = 30
TEMPERATURE_FOR_ANSWER_ONLY = 0.1
TOP_P_FOR_ANSWER_ONLY = 0.9

MAX_OUTPUT_LEN_REASONING = 100
TEMPERATURE_FOR_REASONING = 0.1
TOP_P_FOR_REASONING = 0.9
# try temperature .2 top_p .7

# ImageQA

IMAGE_H = 512
IMAGE_W = 512

# VideoQA

VIDEO_H = 224
VIDEO_W = 224
VIDEO_FPS = 4
VIDEO_NUM_FRAMES = 16
